services:
  db:
    image: mysql:latest
    restart: always

    environment:
      MYSQL_DATABASE: 'herotozero'
      MYSQL_USER: 'niklas'            # So you don't have to use root, but you can if you like
      MYSQL_PASSWORD: 'test123'       # You can use whatever password you like
      MYSQL_ROOT_PASSWORD: 'test123'  # Password for root access

    ports:
      - '3306:3306'     # <Port exposed> : <MySQL Port running inside container>
    expose:
      - '3306'          # Opens port 3306 on the container
 
    volumes: 
      - herotozero-data:/var/lib/mysql  # Where the data will be persisted (doesn't delete on startup of the container)

volumes:
  herotozero-data:  # Names the volume